PD_OPTS=--toc --number-sections --normalize --smart -V geometry="margin=1in" --latex-engine=xelatex -f Markdown

# IMAGES=$(IMGMSC:.msc=.png) $(IMGDOT:.dot=.png)
IMAGES=$(shell tools/mdimages.php -i $(IN) -l -g)

.PHONY: all clean

all: $(OUT)

clean:
	rm -rf $(OUT) $(IMAGES)

builddoc: spec/*.md
	tools/build.sh > $(IN)

images: $(IMAGES)

$(OUT): builddoc images
	tools/mdimages.php -i $(IN) -r | pandoc $(PD_OPTS) -o $(OUT)

%.png: %.msc
	mscgen -T png -o $@ -i $<
	convert $@ -density 75 -units PixelsPerInch $@

%.png: %.dot
	dot -Tpng -o$@ $<
	convert $@ -density 175 -units PixelsPerInch $@

