#PD_OPTS=--toc --number-sections --normalize --smart -V geometry="margin=1in" -f markdown --standalone
PD_OPTS=--toc --number-sections --standalone

# IMAGES=$(IMGMSC:.msc=.png) $(IMGDOT:.dot=.png)
IMAGES=$(shell tools/mdimages.php -i $(CACHE) -l -g)
CACHE=.makedoc.cache
OUT_MD=$(OUT).md
OUT_PDF=$(OUT).pdf

.PHONY: all clean builddoc images

all: $(OUT_MD) $(OUT_PDF)

clean:
	rm -rf $(OUT_PDF) $(OUT_MD) $(IMAGES)

builddoc: $(CACHE)

$(CACHE): spec/*.md
	tools/build.sh > $(CACHE)

images: $(IMAGES)

$(OUT_MD): builddoc images
	tools/mdimages.php -i $(CACHE) -r -o $(OUT_MD)

$(OUT_PDF): $(OUT_MD)
	pandoc $(PD_OPTS) $(OUT_MD) -o $(OUT_PDF)

%.png: %.msc
	mscgen -T png -o $@ -i $<
	convert $@ -density 75 -units PixelsPerInch $@

%.png: %.dot
	dot -Tpng -o$@ $<
	convert $@ -density 175 -units PixelsPerInch $@

